stages:
  - compile
  - test
  - create_image

image: golang:1.13.4

before_script:
  # Create a symbolic link under $GOPATH, this is needed for local build
  # i.e. /go/src/gitlab.com/ykyuen/gitlab-ci-go-build
  - cd $GOPATH/src
  - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
  - cd gitlab.com/$CI_PROJECT_NAMESPACE
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME

compile:
  stage: compile
  tags:
    - privileged
  script:
    - go build -i -v -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/postmanerator
  artifacts:
    paths:
      - mybinary

test:
  stage: test
  tags:
    - privileged
  script:
    - go build test ./...
